name: Prepare

description: Checkout and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'
    - name: Bump npm to version 11
      shell: bash
      run: |
        npm install -g npm@11
    - name: Install dependencies
      shell: bash
      run: |
        npm ci
