name: Deploy to Juno

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Deploy to Juno
        uses: junobuild/juno-action@3684a7942dc273c9e558f72b0ea6c358d5c55e93 # main
        with:
          args: hosting deploy
