name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  update_snapshots:
    runs-on: ubuntu-20.04
    steps:
      - name: Fail if branch is main
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "This workflow should not be triggered with workflow_dispatch on main"
          exit 1

      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PR_AUTOMATION_BOT_PUBLIC_APP_ID }}
          private-key: ${{ secrets.PR_AUTOMATION_BOT_PUBLIC_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npm run playwright:install
      - name: Run Playwright tests
        run: npm run e2e:snapshots
      - name: Commit Playwright updated snapshots
        uses: EndBug/add-and-commit@v9
        if: ${{ github.ref != 'refs/heads/main' }}
        with:
          add: e2e
          default_author: github_actions
          message: "🤖 update snapshots"
